### ISSUE TITLE
Please add support for programatically adding measurements!

### ISSUE THREAD

**Issue by martonmiklos** [saleae/SaleaeSocketApi#2]
Title says all. I am a little bit tired with adding the measurements manually and selecting the proper measurement types. If it could be automated it would be awesome!

Thanks in advance!

**Comment by Marcus10110** [comment]
Thanks for the suggestion!

Are you specifically looking for a socket API call that would let you place and configure a measurement on a specific channel over a specific range, and then query back the measurement results?

Ultimately, we want to make the software 100% controllable from an API of some sort, and I think this would be really cool. 

Feel free to add this and vote for it on our ideas page here:
http://ideas.saleae.com/forums/214303-saleae-ideas/suggestions/5798328

Right now we're not making any public commitments on when these suggestions could be implemented. You can read about our expectations for new feature development here:
http://blog.saleae.com/software-feature-development-expectations/

**Comment by martonmiklos** [comment]
Hi Mark,

Thank you for the fast answer!

At first I would be happy if I could just add measurements programatically (by specifying the channel, start time, end time and the necessary measurement types). 

Retriving the results via API is not mandatory at the moment for me, but it would be awesome if it could be done. 

I have posted this under the ideas forum too. 

Thanks again and keep up your great job!

**Comment by Marcus10110** [comment]
Thanks!
