### ISSUE TITLE
"Skip to" command

### ISSUE THREAD

**Issue by Xasin** [saleae/SaleaeSocketApi#5]
Hello, 

I've recently purchased one of your devices (the Logic 8) and would like to automate some analyzing of circuits.
Your Socket API is a great option to do this, however, I would like the option to zoom in to a specific time region, or maybe set up timing markers at specific points.
This way, my analysis script could give me an option to directly command the software to zoom in to an area in question, which would be easier than having to look for the specific time myself.
I think this would be a fitting addition to the scripting API, but if it is too complex to code in, I can understand.

With kind regards,
  David

**Comment by Marcus10110** [comment]
Hi David, this was added in the 1.2.18 software release, and this socket API sample was added at the same time. There are 3 functions to help with this:
get_capture_range, get_viewstate, and set_viewstate:
https://github.com/saleae/SaleaeSocketApi/blob/master/Doc/Logic%20Socket%20API%20Users%20Guide.md#get-capture-range
