### ISSUE TITLE
Provide ability to query analyzer status

### ISSUE THREAD

**Issue by martonmiklos** [saleae/SaleaeSocketApi#8]
Hi folks,

I needed to came up with an automation for exporting data from the analyzers from a lot of logicdata files. 

After running it through my files I realized that the exporting failed on some files. 
I could open these files and export them manually without any problem.

During this manual session I have noticed one thing: when I opened these files a progress indicator with a percentage is shown here next to the analyzer name:
![kep](https://user-images.githubusercontent.com/1609182/46340073-b27dfb80-c634-11e8-83cf-ffd6d9590fdd.png)

I assume my automation script tried to call EXPORT_ANALYZER while the analyzer still got loaded.

Please provide some API call to be able to verify the analyzer status/loading percentage.

Thanks in advance!

**Comment by TheOnlyStenberg** [comment]
Hi martonmiklos,

> Please provide some API call to be able to verify the analyzer status/loading percentage.

The API has the "is_analyzer_complete" command, is this what you are looking for?

**Comment by martonmiklos** [comment]
@TheOnlyStenberg 
Wow, I do not know how did I missed it...
Thank you so much!
