### ISSUE TITLE
Add Custom command

### ISSUE THREAD

**Issue by SoniaKaudjhis** [saleae/SaleaeSocketApi#9]
I would like to add a command to export result from Decoded Protocols. I am wondering which command to enable to do this 
![image](https://user-images.githubusercontent.com/1808514/47242157-efc7e480-d3bb-11e8-8c54-d015096c7519.png)
![image](https://user-images.githubusercontent.com/1808514/47242191-0837ff00-d3bc-11e8-94ec-e58b96ef6b25.png)

**Special Demands** 
Is it possible to get the list of possible command from API ?

Thanks you for your answer

**Comment by timreyesca** [comment]
Hi. Sorry we don't have a specific command implemented to export results from the Decoded Protocols window.

You may have already seen this, but the list of commands are located in our User's Guide below:
https://github.com/saleae/SaleaeSocketApi/blob/master/Doc/Logic%20Socket%20API%20Users%20Guide.md

By the way, feel free to post this idea on ideas.saleae.com. This is where we officially track new features to implement to our software.

**Comment by timreyesca** [comment]
Please note that you are able to export analyzers one at at time. Hopefully this helps.
https://github.com/saleae/SaleaeSocketApi/blob/master/Doc/Logic%20Socket%20API%20Users%20Guide.md#export-analyzers

**Comment by timreyes** [comment]
Hi. Sorry we don't have a specific command implemented to export results from the Decoded Protocols window.
You may have already seen this, but the list of commands are located in our User's Guide below:
https://github.com/saleae/SaleaeSocketApi/blob/master/Doc/Logic%20Socket%20API%20Users%20Guide.md
By the way, feel free to post this idea on ideas.saleae.com. This is where we officially track new features to implement to our software.

Please note that you are able to export analyzers one at at time. Hopefully this helps.
https://github.com/saleae/SaleaeSocketApi/blob/master/Doc/Logic%20Socket%20API%20Users%20Guide.md#export-analyzers
